name: workflow
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  main-workflow:
    uses: khensel17/github-arc-demo/.github/workflows/01-hello-world.yml@main
    secrets:
      AWX_PASSWORD: ${{ secrets.AWX_PASSWORD }}
